apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp 
spec:
  selector:
    matchLabels:
      app: flask-webapp 
  replicas: 3    
  template:
    metadata:
      labels:
        app: flask-webapp 
    spec:
      containers:
      - name: flask-webapp 
        image: simpalkharga/flask_webapp_simpal:v2
        ports:
        - containerPort: 8080
